let suggestions = [
  "Canal",
  "YouTube",
  "YouTuber",
  "Carros",
  "Facebook",
  "Dev Sandrin",
  "Projetos CSS",
  "Tecnologia",
  "Jogos",
  "Notícias",
  "Moda",
  "Maquiagem",
  "Viagens",
  "Receitas",
  "Fitness",
  "Saúde",
  "Finanças",
  "Aprender programação",
  "Dicas de estudo",
  "Filmes",
  "Séries",
  "Livros",
  "Música",
  "Esportes",
  "Animais de estimação",
  "Fotografia",
  "Arte",
  "Design gráfico",
  "Marketing digital",
  "Empreendedorismo",
  "Culinária",
  "Dicas de produtividade",
  "Ciência",
  "História",
  "Curiosidades",
  "Idiomas",
  "Cursos online",
  "Programação web",
  "Desenvolvimento mobile",
  "Inteligência artificial",
  "Machine learning",
  "Realidade virtual",
  "Cinema",
  "Tendências",
  "Maquiagem",
  "Beleza",
  "Estilo de vida",
  "Arquitetura",
  "Viagens",
  "Carreira profissional",
  "Freelancer",
  "Trabalho remoto",
  "Concursos públicos",
  "Política",
  "Meio ambiente",
  "Sustentabilidade",
  "Educação",
  "Voluntariado",
  "Família",
  "Relacionamentos",
  "Casamento",
  "Parentalidade",
  "Conselhos amorosos",
  "Saúde mental",
  "Meditação",
  "Yoga",
  "Exercícios em casa",
  "Dieta",
  "Receitas saudáveis",
  "Moda sustentável",
  "Beleza natural",
  "Cuidados com a pele",
  "Produtos eco-friendly",
  "Carros elétricos",
  "Tecnologia limpa",
  "Energias renováveis",
  "Viagens sustentáveis",
  "Ecoturismo",
  "Aventuras ao ar livre",
  "Camping",
  "Esportes radicais",
  "Ciclismo",
  "Corrida",
  "Esportes aquáticos",
  "Futebol",
  "Basquete",
  "Voleibol",
  "Tênis",
  "Gastronomia internacional",
  "Culinária regional",
  "Comida vegetariana",
  "Receitas veganas",
  "Comida italiana",
  "Comida asiática",
  "Comida mexicana",
  "Cervejas artesanais",
  "Vinhos",
  "Cocktails",
  "Arte moderna",
  "Pintura",
  "Escultura",
  "Fotografia de paisagem",
  "Ilustração",
  "Design de interiores",
  "Arte urbana",
  "Artesanato",
  "DIY (Faça você mesmo)",
  "Decoração",
  "Mercado financeiro",
  "Investimentos",
  "Finanças pessoais",
  "Economia",
  "Criptomoedas",
  "Blockchain",
  "Startups",
  "Inovação",
  "Negócios sociais",
  "Marketing de afiliados",
  "SEO",
  "Redes sociais",
  "Gestão do tempo",
  "Motivação",
  "Desenvolvimento pessoal",
  "Autoajuda",
  "Meditação guiada",
  "Mindfulness",
  "Desenvolvimento de habilidades",
  "Aprendizado contínuo",
  "Educação online",
  "Intercâmbio cultural",
  "Aprender um novo idioma",
  "História da arte",
  "Literatura clássica",
  "Poesia contemporânea",
  "Autores favoritos",
  "Música indie",
  "Bandas alternativas",
  "Instrumentos musicais",
  "Compositores clássicos",
  "Ciência ficção",
  "Fantasia",
  "Romance histórico",
  "Livros de não-ficção",
  "Biografias",
  "Mistério",
  "Suspense",
  "Ação",
  "Comédia",
  "Drama",
  "Animação",
  "Documentários",
  "Filmes clássicos",
  "Cultura pop",
  "Gamer",
  "Jogos de tabuleiro",
  "Video games",
  "E-sports",
  "Consoles de videogame",
  "Astronomia",
  "Física",
  "Química",
  "Biologia",
  "Geologia",
  "Ecologia",
  "Arqueologia",
  "Antropologia",
  "Sociologia",
  "Psicologia",
  "Filosofia",
  "Ética",
  "Teologia",
  "Religião",
  "Mitologia",
  "Ficção científica",
  "Invenções",
  "Descobertas científicas",
  "Espaço",
  "Astronáutica",
  "Aviação",
  "História militar",
  "Guerras mundiais",
  "Conflitos históricos",
  "Armas e equipamentos militares",
  "Medicina",
  "Doenças comuns",
  "Remédios naturais",
  "Fitness em casa",
  "Exercícios aeróbicos",
  "Treino de força",
  "Treino de flexibilidade",
  "Caminhadas",
  "Corrida",
  "Ioga",
  "Pilates",
  "Nutrição",
  "Alimentação saudável",
  "Vida sem glúten",
  "Receitas sem lactose",
  "Vida sem açúcar",
  "Dieta cetogênica",
  "Alimentos orgânicos",
  "Receitas low carb",
  "Bebidas saudáveis",
  "Smoothies",
  "Chás",
  "Café",
  "Sucos naturais",
  "Suplementos",
  "Medicina alternativa",
  "Acupuntura",
  "Homeopatia",
  "Aromaterapia",
  "Terapia cognitivo-comportamental",
  "Psicoterapia",
  "Terapia de casal",
  "Autoconhecimento",
  "Mindfulness",
  "Meditação guiada",
  "Educação emocional",
  "Bem-estar",
  "Felicidade",
  "Relacionamentos saudáveis",
  "Comunicação eficaz",
  "Autoestima",
  "Ansiedade",
  "Estresse",
  "Depressão",
  "Transtornos alimentares",
  "Insônia",
  "Hobbies",
  "Arte marcial",
  "Dança",
  "Pintura",
  "Desenho",
  "Escultura",
  "Artesanato",
  "Fotografia",
  "Cozinha",
  "Jardinagem",
  "Viajar",
  "Camping",
  "Ciclismo",
  "Corrida",
  "Natação",
  "Pesca",
  "Observação de aves",
  "Leitura",
  "Escrita criativa",
  "Teatro",
  "Cinema",
  "Música",
  "Coleção de selos",
  "Numismática",
  "Colecionar arte",
  "Filatelia",
  "Colecionar antiguidades",
  "DIY (Faça você mesmo)",
  "Tricô",
  "Crochê",
  "Costura",
  "Marcenaria",
  "Modelagem de argila",
  "Puzzles",
  "Jogos de tabuleiro",
  "Xadrez",
  "Poker",
  "Culinária internacional",
  "Comida japonesa",
  "Comida tailandesa",
  "Comida indiana",
  "Comida francesa",
  "Comida espanhola",
  "Comida brasileira",
  "Comida africana",
  "Comida árabe",
  "Vinhos",
  "Cervejas artesanais",
  "Cocktails",
  "Churrasco",
  "Receitas de família",
  "Receitas rápidas",
  "Receitas de sobremesas",
  "Receitas vegetarianas",
  "Receitas veganas",
  "Receitas sem glúten",
  "Receitas low carb",
  "Receitas saudáveis para crianças",
  "Receitas de drinks",
  "Receitas de smoothies",
  "Receitas de cafés especiais",
  "Receitas de chás",
  "Receitas de sucos naturais",
  "Receitas de pratos típicos",
];
