const suggestions = [
    "ANO NOVO", "BINARIOS", "BUSCADOR AUTOCOMPLETE", "CADASTRO", "CONVERTER PARA UPPER VOLUME 1", 
    "CONVERTER PARA UPPER VOLUME 2", "EDITOR EMBED", "ESTATISTICAS DO GITHUB", "FORMATAR LETRAS", 
    "GERADOR DE SENHAS", "IFRAME DO YOUTUBE VOLUME 1", "IFRAME DO YOUTUBE VOLUME 2", "IFRAME SITES", 
    "REPL COM PYSCRIPT", "RODA DA SORTE", "VOZ DO NARRADOR", "WORD"
];
