const suggestions = [
    "ALISTAMENTO MILITAR", "ANATOMIA DA DIVISAO", "ANO BISSEXTO", "CALCULADORA", "CALCULAR HIPOTENUSA", "CALCULAR IMC", "CALCULAR MDC", "CALCULAR MEDIA", "CALCULAR MMC", "CALCULAR PA", "CALCULAR PG", "CALCULAR PORCETAGEM", "CALCULAR SCT", "CONTADOR DE STRING COM PYSCRIPT", "CONVERSOR DE TEMPERATURA", "CONVERSOR DE TEMPO", "EQUACOES DO 1 GRAU", "EQUACOES DO 2 GRAU", "IDADE EM ANOS", "IMPA E PAR COM PYSCRIPT", "INVESTIMENTO", "PALINDROMO", "PODE VOTAR", "POTENCIACAO", "REGRA DE TRES", "TABUADA", "VERIFICAR TRIANGULO"        
];
