let responses = {
    // SAUDAÇÃO:
    "oi": "Oi! Como posso ajudar você hoje?",
    "olá": "Olá! Em que posso ser útil?",
    "tchau": "Tchau! Tenha um ótimo dia!",
    "bom dia": "Bom dia! Como você está?",
    "boa tarde": "Boa tarde! Espero que seu dia esteja indo bem.",
    "boa noite": "Boa noite! Precisa de alguma coisa antes de dormir?",
    "ajuda": "Claro! Em que posso ajudar?",

    // SOBRE NAMORO:
    "você namora?": "Eu sou um bot, então namoro não faz parte da minha programação. 😅",
    "como começar um namoro?": "A melhor forma de começar um namoro é ser você mesmo(a) e demonstrar respeito e sinceridade.",
    "dicas para namoro": "A chave para um bom relacionamento é a comunicação aberta, confiança e compreensão mútua. ❤️",
    "estou apaixonado(a)": "Que bom! Apaixonar-se é uma sensação incrível. Vá com calma e seja sincero(a) com seus sentimentos!",
    "namoro à distância funciona?": "Namoro à distância pode ser desafiador, mas com confiança, comunicação e comprometimento, pode funcionar!",
    "termino de namoro": "Términos são difíceis, mas é importante cuidar de si mesmo(a) e respeitar o tempo para superar. Tudo vai melhorar!",
    "como lidar com ciúmes?": "Ciúmes são naturais, mas a confiança e o diálogo são fundamentais para lidar com eles de maneira saudável.",
    "como confiar no parceiro(a)?": "Confiança é construída com tempo e transparência. Converse sobre suas preocupações de forma aberta.",
    "o que é amor verdadeiro?": "Amor verdadeiro é baseado no respeito, confiança e apoio mútuo.",
    "como saber se estou apaixonado(a)?": "Se você pensa na pessoa o tempo todo e se sente bem quando está perto dela, é um sinal de que você está apaixonado(a)!",
    "como demonstrar amor?": "Pequenos gestos, palavras de carinho e apoio emocional são formas de demonstrar amor.",
    "qual o segredo para um namoro duradouro?": "O segredo é paciência, comunicação e manter a chama da paixão acesa.",
    "qual a importância da confiança?": "Confiança é a base de qualquer relacionamento saudável. Sem ela, fica difícil construir algo sólido.",
    "como superar o fim de um relacionamento?": "O tempo é essencial. Permita-se sentir, busque apoio de amigos e faça coisas que você ama.",
    "quais os sinais de um relacionamento abusivo?": "Ciúmes excessivo, controle, desrespeito e manipulação são sinais de um relacionamento abusivo. Procure ajuda se necessário.",
    "como melhorar a comunicação no namoro?": "Escute ativamente, seja claro(a) sobre seus sentimentos e evite culpar o outro nas discussões.",
    "como lidar com desentendimentos?": "Converse com calma, entenda o ponto de vista do outro e busque soluções em conjunto.",
    "diferença entre paixão e amor": "A paixão é intensa, mas passageira. O amor é profundo e duradouro.",
    "como manter a chama do amor acesa?": "Faça surpresas, demonstre carinho diariamente e busque novas formas de se conectar.",
    "como saber se é hora de terminar?": "Se não há mais respeito, confiança ou amor, pode ser um sinal de que é hora de seguir em frente.",
    "namoro e redes sociais": "É importante ter limites claros e respeitar a privacidade um do outro nas redes sociais.",
    "como lidar com um parceiro(a) ciumento(a)?": "Converse abertamente sobre os sentimentos dele(a) e reforce a importância da confiança.",
    "como fazer uma surpresa romântica?": "Conheça os gostos do seu parceiro(a) e planeje algo pessoal, seja um jantar, uma carta ou um passeio especial.",
    "quais são as bases de um relacionamento saudável?": "Confiança, respeito, comunicação e carinho são as bases de um relacionamento saudável.",
    "diferença entre relacionamento saudável e tóxico": "Um relacionamento saudável traz crescimento e felicidade, enquanto o tóxico suga sua energia e causa sofrimento.",
    "como lidar com a saudade no namoro à distância?": "Façam videochamadas, mantenham contato frequente e planejem visitas para manter a conexão.",
    "como reatar com ex?": "Se ambos estiverem dispostos a mudar e crescer, pode funcionar. Mas é importante ter certeza de que vale a pena.",
    "namoro e diferenças culturais": "O respeito pelas diferenças e o diálogo são fundamentais em um relacionamento intercultural.",
    "como falar sobre problemas no namoro?": "Escolha um momento tranquilo e use uma abordagem gentil, focando em soluções ao invés de culpabilizar.",
    "devo perdoar uma traição?": "Perdoar é uma escolha pessoal, mas exige muito trabalho para reconstruir a confiança.",
    "como evitar brigas no namoro?": "Tenha paciência, escute antes de falar e não deixe pequenos problemas acumularem.",
    "namoro e família": "É importante encontrar um equilíbrio entre o relacionamento com seu parceiro(a) e a relação com sua família.",
    "quando é hora de apresentar o parceiro(a) à família?": "Quando o relacionamento estiver firme e vocês dois se sentirem preparados.",
    "como lidar com diferenças de opinião?": "Aceitar que vocês não precisam concordar em tudo e respeitar as opiniões diferentes ajuda a manter a harmonia.",
    "namoro no trabalho": "Estabeleça limites claros para que o relacionamento pessoal não interfira no profissional.",
    "namoro e dinheiro": "Converse abertamente sobre questões financeiras e busque um equilíbrio nas responsabilidades.",
    "como manter a individualidade no namoro?": "É importante ter hobbies e tempo pessoal, além de momentos com o parceiro(a).",
    "qual a importância do respeito no namoro?": "Respeito é fundamental para um relacionamento saudável. Ele mantém a confiança e a harmonia.",
    "como lidar com um término inesperado?": "Dê-se tempo para processar, não busque culpados e concentre-se em cuidar de si mesmo(a).",
    "como planejar o futuro juntos?": "Conversem sobre objetivos de vida, carreira e família para alinhar expectativas.",
    "como saber se a pessoa é a certa para mim?": "Se vocês compartilham valores, se respeitam e se apoiam, é um bom sinal de que estão no caminho certo.",
    "como fortalecer a conexão emocional?": "Passe tempo de qualidade juntos, escute ativamente e seja vulnerável ao compartilhar sentimentos.",
    "como lidar com um parceiro(a) possessivo(a)?": "Defina limites saudáveis e converse sobre a importância da confiança mútua.",
    "como pedir desculpas no namoro?": "Seja sincero(a), reconheça o erro e mostre disposição para mudar.",
    "namoro ou amizade?": "Se houver sentimentos românticos envolvidos, é importante ser honesto(a) consigo mesmo(a) e com o outro.",
    "quando é hora de dar um tempo?": "Quando vocês precisam de espaço para refletir sobre o relacionamento e suas próprias necessidades.",
    "como melhorar a intimidade no namoro?": "A intimidade emocional vem com confiança e comunicação aberta. A física, com respeito e carinho.",
    "namoro e hobbies diferentes": "Incentivem os hobbies um do outro e busquem atividades que possam fazer juntos.",
    "como evitar a rotina no namoro?": "Inovem nos encontros, façam surpresas e continuem descobrindo coisas novas juntos.",
    "como reconquistar o parceiro(a)?": "Mostre que você mudou, seja sincero(a) e tenha paciência no processo de reconquista.",
    "qual a importância do humor no namoro?": "Rir juntos fortalece a conexão e ajuda a superar momentos difíceis.",
    "como lidar com inseguranças no namoro?": "Converse sobre suas inseguranças e trabalhe em sua autoestima para fortalecer o relacionamento.",
    "como manter o romantismo no namoro longo?": "Continue com gestos de carinho, planeje momentos especiais e mantenha o interesse mútuo.",
    "como saber se estou em um relacionamento tóxico?": "Se você sente mais sofrimento do que felicidade, pode ser um sinal de toxicidade.",
    "como superar a timidez no namoro?": "Converse abertamente sobre seus sentimentos e vá aos poucos se abrindo para o parceiro(a).",
    "namoro e religião": "Se houver diferenças religiosas, é importante ter respeito e buscar um equilíbrio entre as crenças.",
    "namoro e filhos": "Conversem sobre o desejo de ter filhos, timing e como ambos veem a criação dos mesmos.",
    "como expressar amor em palavras?": "Seja sincero(a), fale sobre o que admira e como a pessoa te faz sentir.",
    "como saber se ele(a) gosta de mim?": "Preste atenção em gestos, olhares e como a pessoa se comporta ao seu redor.",
    "como manter a confiança em um relacionamento?": "Seja transparente, cumpra suas promessas e sempre converse sobre seus sentimentos.",
    "namoro e vida profissional": "Estabeleçam um equilíbrio entre trabalho e tempo juntos, sem deixar que uma área prejudique a outra.",
    "como lidar com pressão no namoro?": "Se sentir pressão, converse com seu parceiro(a) e busque maneiras de aliviar essa tensão.",
    "como melhorar a empatia no namoro?": "Coloque-se no lugar do outro e procure entender suas emoções e pontos de vista.",
    "quais as maiores dificuldades no namoro?": "Ciúmes, falta de comunicação e expectativas diferentes podem ser grandes desafios.",
    "namoro e casamento": "Casamento pode ser o próximo passo, mas é importante alinhar expectativas antes de tomar essa decisão.",
    "namoro de longa data": "Mantenha o esforço mútuo, a comunicação e o carinho para que o relacionamento continue forte.",
    "como saber se o amor acabou?": "Se não há mais interesse, carinho ou desejo de fazer o relacionamento funcionar, pode ser um sinal de que o amor se foi.",
    "como lidar com a solidão no namoro?": "Converse com seu parceiro(a) sobre suas necessidades emocionais e procure fortalecer a conexão.",
    "como saber se sou dependente emocionalmente?": "Se você sente que sua felicidade depende exclusivamente da outra pessoa, pode ser um sinal de dependência emocional.",
    "namoro e autoestima": "Ter uma autoestima saudável ajuda a manter o equilíbrio no relacionamento e evita dependências excessivas.",
    "como melhorar o namoro?": "Conversem abertamente sobre expectativas, dediquem tempo de qualidade juntos e continuem se esforçando para agradar um ao outro.",
    "como lidar com o medo de perder o parceiro(a)?": "O medo é normal, mas a confiança mútua e a comunicação aberta podem ajudar a minimizar essas inseguranças.",
    
    // CASO PADRÃO:
    "default": "Desculpe, não tenho uma resposta para isso. Pode tentar outra pergunta?"
};
