const suggestions = [
    "ANALISADOR DE NUMEROS", "CONTADOR", "GOOGLE GRASS", "HORARIO ATUAL", "IMAGEM FLEXIVEL", "LÂMPADA", "MASCOTE DO ANDROID", "MENU RESPONSIVO", "POEMA CORDEL", "REDES SOCIAIS 01", "REDES SOCIAIS 02", "SITE MOBILE", "TABELA RESPONSIVA", "TABUADA", "TELA DE LOGIN", "VERIFICADOR DE IDADE", "VIDEOS IFRAME"       
];

